### PR TITLE
Import

### PR DESCRIPTION
**Pull request by Djeisen642**
Ability to import guests

### CODE REVIEW

**Comment by anjosh** [comment]
@TatsumiSuenaga could you review this please?

**Comment by TatsumiSuenaga** [comment]
This is coming from someone that is unfamiliar, and cannot run the dev server (some conflict between the htm project files and npm), but the code looks fine.

**Comment by Djeisen642** [comment]
Hey @anjosh, I've updated it to do some smart selections. Check again?

**Comment by anjosh** [comment]
Jason this looks good. It doesn't currently work for the spreadsheet that most TMs will likely be using. Could you kindly update it to work for that? I made some small changes to get there and rebased with master.

**Comment by anjosh** [comment]
Here's the spreadsheet I'm talking about: https://drive.google.com/file/d/0B_uVEsYLmMO6VEJJa08xb2M0Zl9pMmNnb0lRRE55aWozdHRZ/view

**Comment by Djeisen642** [comment]
Ok. This is a different spreadsheet than I must have seen before. We might need to ask the user to tell us where the headers start on their spreadsheet if there are going to be many different spreadsheets.
``` javascript
let persons = this.sheetdata.slice(1)
```
needs to change to
``` javascript
let persons = this.sheetdata.slice(2)
```
for this spreadsheet. And I guess there needs to be a filter for people that don't have a fullname.
``` javascript
persons.filter(person => !!person.fullname);
```

**Comment by anjosh** [comment]
Ok I'll try that.

**Comment by anjosh** [comment]
@Djeisen642 made some edits please take a look if you get a chance.

**Comment by anjosh** [comment]
Gonna go ahead an merge. feel free to take a look and give some comments if you have any.

**Pull request merged**
